WITH PROMEDIO_GENERAL AS (
	SELECT AVG(PRECIO_ORI) AS PROMEDIO_ORIGINAL_GLOBAL
	FROM LIBRO
	)
SELECT 
	TIPO, 
	AVG(PRECIO_ORI) AS PROMEDIO_PRECIOS_ORI
FROM LIBRO
GROUP BY TIPO
HAVING AVG(PRECIO_ORI) > (SELECT PROMEDIO_ORIGINAL_GLOBAL FROM PROMEDIO_GENERAL)