SELECT
	SUM(PRECIO_ORI + PRECIO_ACT) AS SUMA_PRECIOS_TOTALES,
	AVG(PRECIO_ORI + PRECIO_ACT) AS PROM_PRECIOS_TOTALES,
	MIN(PRECIO_ACT - PRECIO_ORI) AS MIN_DIF_PRECIO,
	MAX(PRECIO_ACT - PRECIO_ORI) AS MAX_DIF_PRECIO
FROM LIBRO
WHERE EDICION > 1970