SELECT
	LIBRO.NRO_LIBRO,
	LIBRO.TITULO,
	PRESTAMO.NRO_COPIA,
	COUNT(PRESTAMO.NRO_LIBRO) AS CANTIDAD_PRESTAMOS
	/*ESTO ES LO MISMO,
	COUNT(PRESTAMO.NRO_LIBRO) AS CANTIDAD_PRESTAMOS
	*/
FROM LIBRO
INNER JOIN PRESTAMO ON LIBRO.NRO_LIBRO = PRESTAMO.NRO_LIBRO
GROUP BY LIBRO.NRO_LIBRO, LIBRO.TITULO, PRESTAMO.NRO_COPIA
