SELECT
	LIBRO.NRO_LIBRO,
	LIBRO.TITULO,
	COUNT(PRESTAMO.NRO_LIBRO) AS CANTIDAD_PRESTAMOS

FROM LIBRO
INNER JOIN PRESTAMO ON LIBRO.NRO_LIBRO = PRESTAMO.NRO_LIBRO
WHERE PRESTAMO.F_DEVOL >= 2012
GROUP BY LIBRO.NRO_LIBRO, LIBRO.TITULO