SELECT
	LECTOR.NRO_LECTOR,
	LECTOR.NOMBRE,
	COUNT(PRESTAMO.NRO_LIBRO) AS CANTIDAD_PRESTAMOS
FROM LECTOR
INNER JOIN PRESTAMO ON LECTOR.NRO_LECTOR = PRESTAMO.NRO_LECTOR
GROUP BY LECTOR.NRO_LECTOR, LECTOR.NOMBRE
