SELECT
	LECTOR.NRO_LECTOR,
	LECTOR.NOMBRE,
	LIBRO.NRO_LIBRO,
	LIBRO.TITULO,
	PRESTAMO.F_PREST
FROM LECTOR
INNER JOIN PRESTAMO ON LECTOR.NRO_LECTOR = PRESTAMO.NRO_LECTOR
INNER JOIN LIBRO ON LIBRO.NRO_LIBRO = PRESTAMO.NRO_LIBRO
WHERE PRESTAMO.F_DEVOL IS NOT NULL