SELECT
	PRESTAMO.NRO_LIBRO,
	LIBRO.TITULO,
	PRESTAMO.NRO_COPIA,
	COUNT(*) AS CANTIDAD_PRESTAMOS

FROM PRESTAMO
INNER JOIN LIBRO ON LIBRO.NRO_LIBRO = PRESTAMO.NRO_LIBRO
GROUP BY PRESTAMO.NRO_LIBRO, LIBRO.TITULO, PRESTAMO.NRO_COPIA
HAVING COUNT(*) > 1