SELECT
	LECTOR.NRO_LECTOR,
	LECTOR.NOMBRE,
	LIBRO.NRO_LIBRO,
	LIBRO.TITULO,
	LIBRO.TIPO,
	PRESTAMO.F_PREST
FROM PRESTAMO
INNER JOIN LECTOR ON PRESTAMO.NRO_LECTOR = LECTOR.NRO_LECTOR
INNER JOIN LIBRO ON PRESTAMO.NRO_LIBRO = LIBRO.NRO_LIBRO
WHERE PRESTAMO.F_DEVOL IS NOT NULL 
AND LIBRO.TIPO IN ('NO', 'CU')