SELECT
	TITULO,
	F_PREST,
	F_DEVOL
FROM LIBRO
INNER JOIN PRESTAMO ON LIBRO.NRO_LIBRO = PRESTAMO.NRO_LIBRO

/*
SE PUEDE HACER ASI, REFERENCIANDO A QUE TABLA SE APUNTA CON L Y P

SELECT
	L.TITULO,
	P.F_PREST,
	P.F_DEVOL
FROM LIBRO L
INNER JOIN PRESTAMO P ON L.NRO_LIBRO = P.NRO_LIBRO
*/
