-- Consulta que muestra todos los campos de todas las tablas
SELECT *
FROM LIBRO
LEFT JOIN COPIAS ON LIBRO.NRO_LIBRO = COPIAS.NRO_LIBRO
LEFT JOIN PRESTAMO ON COPIAS.NRO_LIBRO = PRESTAMO.NRO_LIBRO AND COPIAS.NRO_COPIA = PRESTAMO.NRO_COPIA
LEFT JOIN LECTOR ON PRESTAMO.NRO_LECTOR = LECTOR.NRO_LECTOR;